### ISSUE TITLE
下载出错 KeyError: 'nickname'

### ISSUE THREAD

**Issue by cws999** [jiji262/douyin-downloader#2]
[  提示  ]:重复请求该接口10s, 仍然未获取到数据
Traceback (most recent call last):
  File "/abcd/douyin-downloader-main/DouYinCommand.py", line 361, in <module>
    main()
  File "/abcd/douyin-downloader-main/DouYinCommand.py", line 284, in main
    nickname = utils.replaceStr(data['user']['nickname'])
KeyError: 'nickname'

不会编程，这个怎么办

**Comment by omina91** [comment]
@jiji262 Can you fix it please?

**Comment by cws999** [comment]
> @jiji262 Can you fix it please?

I don't know Python and C

**Comment by jiji262** [comment]
更新后重试
